#!/bin/sh

set -e

./log Installing APT configuration
cp -r overlay/etc/apt /etc

./log Updating package lists
apt-get -qq update

./log Upgrading packages
apt-get -qq upgrade

./package zsh
./package mosh
./package htop
./package mutt
./package tmux
./package nginx
./package screen
./package cowsay
./package figlet
./package toilet
./package fortune
./package cmatrix
./package debconf-utils
./package exim4-daemon-light

./log Copying overlay to root filesystem
cp -r overlay/* /

./log Stopping nginx
/etc/init.d/nginx stop

./log Fixing permissions for /var/www
chown -R www-data:www-data /var/www
chmod 6777 /var/www
chmod -R 6775 /var/www/www.uniirc.com

./log Starting nginx
/etc/init.d/nginx start

./log Stopping exim4
/etc/init.d/exim4 stop

./log Importing debconf configuration values
for i in debconf/*; do
	debconf-set-selections < "$i"
done

./log Starting exim4
/etc/init.d/exim4 start

./log Limit nproc to 100 for all users except root
echo '* hard nproc 100' > /etc/security/limits.conf

./log Allowing members of sudo to sudo without password
echo '%sudo ALL = NOPASSWD: ALL' > /etc/sudoers.d/sudogroup

./lockdown root
./lockdown admin

for i in ssh/*; do
	./user "`basename "$i" .pub`"
done

./log Rebooting server, as setup is complete
reboot
