#!/bin/sh

set -e

./log "$1: setting shell to /bin/false to discourage shell usage"
chsh -s /bin/false "$1" < /dev/null

./log "$1: disabling password to prevent password-based login"
passwd -l "$1"

./log "$1: deleting authorized_keys to prevent SSH usage"
if [ "$1" = "root" ]; then
	rm -f "/root/.ssh/authorized_keys"
else
	rm -f "/home/$1/.ssh/authorized_keys"
fi
